import {api,esc,safeUrl} from './control-shared.js';
import {renderContent} from './content-render.js';
const editing=new URLSearchParams(location.search).has('editor');
const preview=new URLSearchParams(location.search).has('preview');
function installTracking(m){
 if(!m.ga&&!m.pixel)return;
 const enable=()=>{if(window.ccMarketing)return;window.ccMarketing=true;
 if(/^G-[A-Z0-9]+$/.test(m.ga)){const s=document.createElement('script');s.async=true;s.src='https://www.googletagmanager.com/gtag/js?id='+encodeURIComponent(m.ga);document.head.append(s);window.dataLayer=window.dataLayer||[];window.gtag=function(){window.dataLayer.push(arguments);};window.gtag('js',new Date());window.gtag('config',m.ga);}
 if(/^\d{5,30}$/.test(m.pixel)){const f=window.fbq=function(){f.callMethod?f.callMethod.apply(f,arguments):f.queue.push(arguments);};f.queue=[];f.loaded=true;f.version='2.0';const s=document.createElement('script');s.async=true;s.src='https://connect.facebook.net/en_US/fbevents.js';document.head.append(s);f('init',m.pixel);f('track','PageView');}
 };
 if(localStorage.getItem('w24-marketing')==='yes'){enable();return;}if(localStorage.getItem('w24-marketing')==='no')return;
 const b=document.createElement('div');b.style.cssText='position:fixed;bottom:90px;left:16px;right:16px;z-index:100;background:#202125;border:1px solid #666;padding:20px;max-width:560px;color:white';b.innerHTML='<p>อนุญาตคุกกี้เพื่อวัดผลและปรับปรุงการตลาดหรือไม่?</p><button class="button" data-yes>อนุญาต</button> <button class="button outline" data-no>ไม่อนุญาต</button>';document.body.append(b);b.querySelector('[data-yes]').onclick=()=>{localStorage.setItem('w24-marketing','yes');enable();b.remove();};b.querySelector('[data-no]').onclick=()=>{localStorage.setItem('w24-marketing','no');b.remove();};
}
const original=document.querySelector('#w24-original')?.innerHTML||document.querySelector('main').innerHTML;
const sourceMain=document.createElement('main');sourceMain.innerHTML=original;
const initialSections=[...sourceMain.querySelectorAll('section[data-cc]')].map(e=>({id:e.dataset.cc,title:e.querySelector('h1,h2')?.textContent.trim()||e.id,hidden:false,type:'original'}));
const baseSections=new Map([...sourceMain.querySelectorAll('section[data-cc]')].map(e=>[e.dataset.cc,e.outerHTML]));
let current;
const text=(q,v)=>document.querySelectorAll(q).forEach(e=>e.textContent=v);
const setMeta=(name,value,property=false)=>{let e=document.head.querySelector(`meta[${property?'property':'name'}="${name}"]`);if(!e){e=document.createElement('meta');e.setAttribute(property?'property':'name',name);document.head.append(e);}e.content=value||'';};
export function render(c,slug='home'){
 current=c;const page=renderContent(document,c,slug,original,baseSections);
 installLead();if(!editing&&!preview){installTracking(c.marketing||{});if(!window.ccTracked){window.ccTracked=true;api('event',{kind:'view',page:page.slug}).catch(()=>{});}}
 bindGallery();
}
function bindGallery(){document.querySelectorAll('.photo-open').forEach(b=>b.onclick=()=>{const d=document.querySelector('#photo-dialog'),i=b.querySelector('img');d.querySelector('img').src=i.src;d.querySelector('img').alt=i.alt;d.querySelector('.modal-caption').textContent=i.alt;d.showModal();});document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('.work-card').forEach(x=>x.hidden=b.dataset.filter!=='all'&&x.dataset.category!==b.dataset.filter);});}
function installLead(){const holder=document.querySelector('#contact .brief');if(!holder)return;holder.innerHTML='<h3>ฝากรายละเอียดให้เราติดต่อกลับ</h3><form id="cc-lead"><label>ชื่อ<input name="name" required maxlength="120" autocomplete="name"></label><label>เบอร์โทร / LINE / อีเมล<input name="contact" required maxlength="200"></label><label>รายละเอียดงาน<textarea name="message" required maxlength="3000" rows="4"></textarea></label><input name="website" tabindex="-1" autocomplete="off" style="display:none"><label class="cc-check"><input type="checkbox" name="consent" required>ยินยอมให้ Wellsound24 ใช้ข้อมูลนี้เพื่อติดต่อกลับเรื่องงาน</label><button class="button">ส่งรายละเอียด</button><p role="status"></p></form>';holder.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.target,button=f.querySelector('button'),status=f.querySelector('[role=status]');if(editing||preview){status.textContent='นี่คือตัวอย่าง แบบฟอร์มจะส่งข้อมูลได้หลังเผยแพร่';return;}button.disabled=true;try{await api('lead',{...Object.fromEntries(new FormData(f)),consent:f.consent.checked});status.textContent='ส่งข้อความแล้ว ทีมงานจะติดต่อกลับครับ';f.reset();}catch(err){status.textContent=err.message;}finally{button.disabled=false;}};}
const style=document.createElement('style');style.textContent='.cc-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:24px}.cc-card{border:1px solid var(--line);background:var(--panel)}.cc-card>div{padding:22px}.cc-card h3{margin:6px 0}.cc-card>img{width:100%;aspect-ratio:1.5;object-fit:cover}.cc-card video,.cc-custom video{max-width:100%}.cc-custom img{max-height:500px}.cc-card p{white-space:normal}.cc-card small{color:var(--muted)}#cc-lead label{display:block;margin:12px 0}#cc-lead input:not([type=checkbox]),#cc-lead textarea{display:block;width:100%;padding:12px;background:#101112;border:1px solid #555;color:white;font:inherit}.cc-check{font-size:14px}[hidden]{display:none!important}';document.head.append(style);
if(preview)document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a||!current)return;const u=new URL(a.href,location.href);if(u.origin===location.origin&&(!u.hash||u.searchParams.has('page'))){e.preventDefault();render(current,u.searchParams.get('page')||'home');window.scrollTo(0,0);}});
if(editing||preview){window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent||e.data?.type!=='cc-render')return;render(e.data.content,e.data.slug);});parent.postMessage({type:'cc-ready',sections:initialSections},location.origin);if(editing){document.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();const el=e.target.closest('[data-cc]');if(!el)return;document.querySelectorAll('[data-cc-selected]').forEach(x=>x.removeAttribute('data-cc-selected'));el.setAttribute('data-cc-selected','');parent.postMessage({type:'cc-select',id:el.dataset.cc,tag:el.tagName,text:el.querySelector('[data-cc]')?null:el.textContent,directText:el.querySelector('[data-cc]')?[...el.childNodes].filter(n=>n.nodeType===3).map(n=>n.textContent).join(''):null,href:el.getAttribute('href'),src:el.getAttribute('src'),alt:el.getAttribute('alt'),style:{color:el.style.color,fontSize:el.style.fontSize,paddingTop:el.style.paddingTop,paddingBottom:el.style.paddingBottom,textAlign:el.style.textAlign}},location.origin);},true);style.textContent+='[data-cc]:hover{outline:1px dashed #ff3758;cursor:crosshair}[data-cc-selected]{outline:3px solid #ed1234!important}';}}
else{const initial=document.querySelector('#w24-published');(initial?Promise.resolve({published:JSON.parse(initial.textContent)}):api('public')).then(d=>{if(d.published)render(d.published,new URLSearchParams(location.search).get('page')||'home');else{installLead();api('event',{kind:'view',page:'home'}).catch(()=>{});}}).catch(()=>{});document.addEventListener('click',e=>{if(e.target.closest('a[href^="tel:"],a[href*="line.me"],a[href*="facebook.com"]'))api('event',{kind:'contact',page:current?.pages[0]?.slug||'home'}).catch(()=>{});});}
