const API='https://sjcxywxixgrpdgeqaepk.supabase.co/functions/v1/admin-license';
let token=sessionStorage.getItem('well_admin_session')||'';
let profile=null,licenses=[],auditLogs=[],verifyEvents=[],editingId=null,activityMode='admin';
const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
const today=()=>new Date().toISOString().slice(0,10);
const plusDays=(iso,n)=>{const base=iso||today();const d=new Date(base+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+Number(n));return d.toISOString().slice(0,10)};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=iso=>{if(!iso)return'-';const [y,m,d]=iso.slice(0,10).split('-');return `${d}/${m}/${y}`};
const fmtDateTime=iso=>iso?new Date(iso).toLocaleString('th-TH',{dateStyle:'short',timeStyle:'short'}):'-';
function daysLeft(x){const a=new Date(today()+'T00:00:00Z'),b=new Date(x+'T00:00:00Z');return Math.round((b-a)/86400000)}
function statusOf(x){if(x.archived)return'archived';if(x.expires_at<today())return'expired';if(!x.enabled)return'disabled';if(x.ib_status!=='approved')return x.ib_status==='pending'?'pending':'blocked';return'active'}
function statusBadge(x){const s=statusOf(x);if(s==='active')return badge('Active','good');if(s==='expired')return badge('Expired','bad');if(s==='disabled')return badge('Disabled','bad');if(s==='pending')return badge('IB Pending','warn');if(s==='archived')return badge('Archived','neutral');return badge('Blocked','warn')}
function ibBadge(v){return v==='approved'?badge('Approved','good'):v==='pending'?badge('Pending','warn'):badge('Rejected','bad')}
function badge(text,kind){return `<span class="badge ${kind}"><span class="status-dot"></span>${esc(text)}</span>`}
function toast(message,kind='good'){const el=document.createElement('div');el.className='toast '+kind;el.textContent=message;$('#toastWrap').appendChild(el);setTimeout(()=>el.remove(),3300)}
function errorText(code){return({invalid_login:'Username หรือ Password ไม่ถูกต้อง',unauthorized:'Session หมดอายุ กรุณาเข้าสู่ระบบใหม่',invalid_input:'ข้อมูล License ไม่ครบหรือไม่ถูกต้อง',duplicate_value:'MT5 Login + Server นี้มี License อยู่แล้ว',invalid_admin_profile:'ข้อมูล Admin ไม่ถูกต้อง',invalid_email:'รูปแบบ Email ไม่ถูกต้อง',current_password_wrong:'Password ปัจจุบันไม่ถูกต้อง',password_too_short:'Password ใหม่ต้องอย่างน้อย 8 ตัวอักษร',server_error:'เซิร์ฟเวอร์ขัดข้อง กรุณาลองใหม่'}[code]||code||'เกิดข้อผิดพลาด')}
async function api(action,payload={},auth=true){const headers={'Content-Type':'application/json'};if(auth&&token)headers.Authorization='Bearer '+token;const r=await fetch(API,{method:'POST',headers,body:JSON.stringify({action,...payload})});const j=await r.json().catch(()=>({ok:false,error:'server_error'}));if(r.status===401&&action!=='login'){forceLogout();throw new Error('unauthorized')}if(!r.ok||!j.ok)throw new Error(j.error||'server_error');return j}
function forceLogout(){token='';profile=null;sessionStorage.removeItem('well_admin_session');$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#loginPassword').value=''}
async function logout(){try{if(token)await api('logout')}catch{}forceLogout()}
function applyProfile(){if(!profile)return;const title=profile.dashboard_title||'Well License Dashboard';document.title=title;$('#sideTitle').textContent=title;$('#sideCompany').textContent=profile.company_name||'Well';$('#adminMiniName').textContent=profile.display_name||'Admin';$('#adminMiniUser').textContent='@'+(profile.username||'admin');$('#adminAvatar').textContent=(profile.display_name||profile.username||'A').trim().charAt(0).toUpperCase();$('#aDisplayName').value=profile.display_name||'';$('#aUsername').value=profile.username||'';$('#aEmail').value=profile.email||'';$('#aCompany').value=profile.company_name||'';$('#aDashboardTitle').value=title;$('#aLastLogin').textContent=fmtDateTime(profile.last_login_at)}
function showApp(){applyProfile();$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');loadAll()}
async function loadAll(){try{$('#apiStatus').textContent='กำลังเชื่อมต่อ...';const [l]=await Promise.all([api('list',{include_archived:$('#showArchived')?.checked||false})]);licenses=l.licenses||[];renderStats();renderLicenses();renderAttention();$('#apiStatus').textContent='API Online'}catch(e){$('#apiStatus').textContent='API Error';toast(errorText(e.message),'bad')}}
function renderStats(){const current=licenses.filter(x=>!x.archived);const active=current.filter(x=>statusOf(x)==='active');const expiring=current.filter(x=>statusOf(x)==='active'&&daysLeft(x.expires_at)>=0&&daysLeft(x.expires_at)<=7);const pending=current.filter(x=>x.ib_status==='pending');const blocked=current.filter(x=>['disabled','expired','blocked'].includes(statusOf(x)));$('#sTotal').textContent=current.length;$('#sActive').textContent=active.length;$('#sExpiring').textContent=expiring.length;$('#sPending').textContent=pending.length;$('#sBlocked').textContent=blocked.length}
function renderAttention(){const list=licenses.filter(x=>!x.archived).map(x=>({x,d:daysLeft(x.expires_at),s:statusOf(x)})).filter(o=>(o.d>=0&&o.d<=7)||o.s==='pending'||o.s==='disabled'||o.s==='expired').sort((a,b)=>a.d-b.d).slice(0,8);$('#attentionList').innerHTML=list.length?list.map(o=>`<div class="attention"><div><div class="attention-title">${esc(o.x.customer_name)} • ${esc(o.x.mt5_login)}</div><div class="attention-meta">${o.s==='pending'?'รอ IB Approved':o.s==='disabled'?'License ถูกปิด':o.s==='expired'?'หมดอายุแล้ว':`เหลือ ${o.d} วัน`} • ${esc(o.x.broker)}</div></div><button class="btn small" data-edit-attention="${o.x.id}">จัดการ</button></div>`).join(''):'<div class="empty">ไม่มีรายการเร่งด่วน 🎉</div>'}
function matchFilter(x,f){const s=statusOf(x),d=daysLeft(x.expires_at);if(f==='all')return!x.archived;if(f==='active')return s==='active';if(f==='pending')return x.ib_status==='pending'&&!x.archived;if(f==='disabled')return s==='disabled';if(f==='expired')return s==='expired';if(f==='expiring')return s==='active'&&d>=0&&d<=7;if(f==='archived')return x.archived;return true}
function renderLicenses(){const q=$('#search').value.trim().toLowerCase(),f=$('#statusFilter').value;const list=licenses.filter(x=>{const hay=`${x.customer_name} ${x.mt5_login} ${x.broker} ${x.server} ${x.license_key}`.toLowerCase();return(!q||hay.includes(q))&&matchFilter(x,f)});$('#licenseRows').innerHTML=list.map(x=>{const d=daysLeft(x.expires_at);const dl=x.archived?'-':d<0?`เกิน ${Math.abs(d)} วัน`:d===0?'วันนี้':`${d} วัน`;const dClass=d<0?'danger-text':'';return `<tr><td><div class="customer-name">${esc(x.customer_name)}</div><div class="subline">${esc(x.notes||'ไม่มีหมายเหตุ')}</div></td><td><b>${esc(x.mt5_login)}</b></td><td><div><b>${esc(x.broker)}</b></div><div class="subline">${esc(x.server)}</div></td><td>${ibBadge(x.ib_status)}</td><td>${fmtDate(x.expires_at)}</td><td><span class="days-left ${dClass}">${dl}</span></td><td><div class="license-key"><code title="${esc(x.license_key)}">${esc(x.license_key)}</code><button class="btn small icon-btn" type="button" data-copy="${esc(x.license_key)}" title="คัดลอก">⧉</button></div></td><td>${statusBadge(x)}</td><td><div class="row-actions"><button class="btn small" data-edit="${x.id}">${x.archived?'ดู':'แก้ไข'}</button>${!x.archived?`<button class="btn small" data-quick-renew="${x.id}" title="ต่ออายุ 30 วัน">+30</button>`:''}</div></td></tr>`}).join('');$('#licenseEmpty').classList.toggle('hidden',list.length>0)}
function switchView(name){$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+name).classList.add('active');const meta={overview:['ภาพรวม','สถานะระบบ License ทั้งหมด'],licenses:['จัดการ License','ค้นหา แก้ไข ต่ออายุ และควบคุมสิทธิ์ลูกค้า'],activity:['ประวัติการทำงาน','Audit Log และการตรวจ License จาก EA'],settings:['ตั้งค่า Admin','แก้ข้อมูลผู้ดูแล Username Password และชื่อระบบ']}[name];$('#pageTitle').textContent=meta[0];$('#pageSubtitle').textContent=meta[1];if(name==='activity')loadActivity();if(name==='settings')applyProfile()}
function openAdd(){editingId=null;$('#licenseForm').reset();$('#licenseModalTitle').textContent='เพิ่ม License ใหม่';$('#licenseModalSub').textContent='กรอกข้อมูลบัญชี MT5 ที่ต้องการอนุญาต';$('#fIb').value='pending';$('#fExpiry').value=plusDays(today(),365);$('#editMeta').classList.add('hidden');$('#renewTools').classList.add('hidden');$('#archiveBtn').classList.add('hidden');$('#restoreBtn').classList.add('hidden');$('#saveLicenseBtn').textContent='สร้าง License';$('#licenseMsg').textContent='';openModal()}
function openEdit(id){const x=licenses.find(v=>v.id===id);if(!x)return;editingId=id;$('#licenseModalTitle').textContent=x.archived?'รายละเอียด License (Archived)':'แก้ไข License';$('#licenseModalSub').textContent=`${x.customer_name} • MT5 ${x.mt5_login}`;$('#fName').value=x.customer_name;$('#fLogin').value=x.mt5_login;$('#fBroker').value=x.broker;$('#fServer').value=x.server;$('#fIb').value=x.ib_status;$('#fExpiry').value=x.expires_at;$('#fNotes').value=x.notes||'';$('#mLicenseKey').textContent=x.license_key;$('#mEnabled').checked=Boolean(x.enabled);$('#mEnabled').disabled=Boolean(x.archived);$('#mEnabledLabel').textContent=x.enabled?'Enabled':'Disabled';$('#editMeta').classList.remove('hidden');$('#renewTools').classList.toggle('hidden',Boolean(x.archived));$('#archiveBtn').classList.toggle('hidden',Boolean(x.archived));$('#restoreBtn').classList.toggle('hidden',!x.archived);$('#saveLicenseBtn').classList.toggle('hidden',Boolean(x.archived));$('#licenseMsg').textContent='';openModal()}
function openModal(){$('#licenseModal').classList.add('open');$('#licenseModal').setAttribute('aria-hidden','false')}
function closeModal(){$('#licenseModal').classList.remove('open');$('#licenseModal').setAttribute('aria-hidden','true');editingId=null}
async function saveLicense(e){e.preventDefault();const payload={customer_name:$('#fName').value.trim(),mt5_login:$('#fLogin').value.trim(),broker:$('#fBroker').value.trim(),server:$('#fServer').value.trim(),ib_status:$('#fIb').value,expires_at:$('#fExpiry').value,notes:$('#fNotes').value.trim()};$('#licenseMsg').textContent='กำลังบันทึก...';try{if(editingId){const current=licenses.find(x=>x.id===editingId);await api('update_license',{id:editingId,...payload});if(current&&Boolean(current.enabled)!==$('#mEnabled').checked)await api('toggle',{id:editingId,enabled:$('#mEnabled').checked});toast('บันทึกการแก้ไขแล้ว')}else{await api('create',payload);toast('สร้าง License สำเร็จ')}closeModal();await loadAll()}catch(err){$('#licenseMsg').textContent=errorText(err.message)}}
async function renew(id,days){try{await api('extend',{id,days});toast(`ต่ออายุ +${days} วันแล้ว`);await loadAll();if(editingId===id){const j=licenses.find(x=>x.id===id);if(j)$('#fExpiry').value=j.expires_at}}catch(e){toast(errorText(e.message),'bad')}}
async function archiveEditing(){if(!editingId)return;const x=licenses.find(v=>v.id===editingId);if(!x||!confirm(`Archive License ของ ${x.customer_name}?\nEA จะถูกปิดใช้งาน แต่ข้อมูลและประวัติยังเก็บไว้`))return;try{await api('archive',{id:editingId});toast('Archive License แล้ว');closeModal();await loadAll()}catch(e){toast(errorText(e.message),'bad')}}
async function restoreEditing(){if(!editingId)return;try{await api('restore',{id:editingId});toast('Restore License แล้ว');closeModal();$('#showArchived').checked=true;await loadAll()}catch(e){toast(errorText(e.message),'bad')}}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('คัดลอก License Key แล้ว')}catch{const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();toast('คัดลอก License Key แล้ว')}}
async function loadActivity(){try{if(activityMode==='admin'){const j=await api('audit_logs',{limit:150});auditLogs=j.logs||[]}else{const j=await api('events',{limit:150});verifyEvents=j.events||[]}renderActivity()}catch(e){$('#activityList').innerHTML='<div class="empty">โหลดประวัติไม่สำเร็จ</div>'}}
function auditLabel(a){return({LOGIN:'เข้าสู่ระบบ',LOGOUT:'ออกจากระบบ',CREATE_LICENSE:'สร้าง License',UPDATE_LICENSE:'แก้ไข License',ENABLE_LICENSE:'เปิด License',DISABLE_LICENSE:'ปิด License',SET_IB:'เปลี่ยนสถานะ IB',EXTEND_LICENSE:'ต่ออายุ License',ARCHIVE_LICENSE:'Archive License',RESTORE_LICENSE:'Restore License',UPDATE_ADMIN:'แก้ข้อมูล Admin'}[a]||a)}
function renderActivity(){if(activityMode==='admin'){const list=auditLogs;$('#activityList').innerHTML=list.length?list.map(x=>{const admin=x.admin_accounts||{};const d=x.details||{};const detail=Object.entries(d).map(([k,v])=>`${k}: ${String(v)}`).join(' • ');return `<div class="activity-item"><div class="activity-time">${fmtDateTime(x.created_at)}</div><div><div class="activity-action">${esc(auditLabel(x.action))}</div><div class="activity-admin">${esc(admin.display_name||admin.username||'Admin')}</div></div><div><div class="activity-detail">${esc(detail||'-')}</div></div></div>`}).join(''):'<div class="empty">ยังไม่มี Audit Log</div>'}else{const list=verifyEvents;$('#activityList').innerHTML=list.length?list.map(x=>`<div class="activity-item"><div class="activity-time">${fmtDateTime(x.created_at)}</div><div><div class="activity-action">${x.event_type==='VERIFY_OK'?badge('VERIFY OK','good'):badge('DENIED','bad')}</div><div class="activity-admin">MT5 ${esc(x.mt5_login||'-')}</div></div><div><div class="activity-detail">${esc(x.broker||'-')} • ${esc(x.server||'-')} • ${esc(x.message||'')}</div></div></div>`).join(''):'<div class="empty">ยังไม่มีการตรวจ License จาก EA</div>'}}
async function saveAdmin(e){e.preventDefault();const np=$('#aNewPassword').value,cp=$('#aConfirmPassword').value;if(np!==cp){$('#adminMsg').textContent='ยืนยัน Password ใหม่ไม่ตรงกัน';return}const payload={display_name:$('#aDisplayName').value.trim(),username:$('#aUsername').value.trim(),email:$('#aEmail').value.trim(),company_name:$('#aCompany').value.trim(),dashboard_title:$('#aDashboardTitle').value.trim(),current_password:$('#aCurrentPassword').value,new_password:np};$('#adminMsg').textContent='กำลังบันทึก...';try{const j=await api('update_admin',payload);profile=j.profile;if(j.session?.token){token=j.session.token;sessionStorage.setItem('well_admin_session',token)}applyProfile();$('#aCurrentPassword').value='';$('#aNewPassword').value='';$('#aConfirmPassword').value='';$('#adminMsg').textContent='บันทึกเรียบร้อย';toast('อัปเดตข้อมูล Admin แล้ว');setTimeout(()=>$('#adminMsg').textContent='',2500)}catch(err){$('#adminMsg').textContent=errorText(err.message)}}

$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginMsg').textContent='กำลังเข้าสู่ระบบ...';$('#loginBtn').disabled=true;try{const j=await api('login',{username:$('#loginUsername').value.trim(),password:$('#loginPassword').value},false);token=j.session.token;profile=j.profile;sessionStorage.setItem('well_admin_session',token);$('#loginMsg').textContent='';$('#loginPassword').value='';showApp()}catch(err){$('#loginMsg').textContent=errorText(err.message)}finally{$('#loginBtn').disabled=false}});
$('#logoutBtn').addEventListener('click',logout);$('#mobileLogoutBtn').addEventListener('click',logout);
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.go)));
$('#addLicenseBtn').addEventListener('click',openAdd);$('#refreshBtn').addEventListener('click',loadAll);$('#search').addEventListener('input',renderLicenses);$('#statusFilter').addEventListener('change',renderLicenses);$('#showArchived').addEventListener('change',loadAll);
$('#licenseForm').addEventListener('submit',saveLicense);$('#closeLicenseModal').addEventListener('click',closeModal);$('#cancelLicenseBtn').addEventListener('click',closeModal);$('#archiveBtn').addEventListener('click',archiveEditing);$('#restoreBtn').addEventListener('click',restoreEditing);$('#copyModalKey').addEventListener('click',()=>copyText($('#mLicenseKey').textContent));$('#mEnabled').addEventListener('change',()=>$('#mEnabledLabel').textContent=$('#mEnabled').checked?'Enabled':'Disabled');
$$('[data-renew]').forEach(b=>b.addEventListener('click',()=>{if(editingId)renew(editingId,Number(b.dataset.renew))}));
$('#licenseRows').addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),renewBtn=e.target.closest('[data-quick-renew]'),copy=e.target.closest('[data-copy]');if(edit)openEdit(edit.dataset.edit);if(renewBtn)renew(renewBtn.dataset.quickRenew,30);if(copy)copyText(copy.dataset.copy)});
$('#attentionList').addEventListener('click',e=>{const b=e.target.closest('[data-edit-attention]');if(b){switchView('licenses');openEdit(b.dataset.editAttention)}});
$$('[data-quick]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.quick;if(a==='add'){switchView('licenses');openAdd()}if(a==='pending'){switchView('licenses');$('#statusFilter').value='pending';renderLicenses()}if(a==='expiring'){switchView('licenses');$('#statusFilter').value='expiring';renderLicenses()}if(a==='activity')switchView('activity')}));
$$('[data-activity]').forEach(b=>b.addEventListener('click',()=>{$$('[data-activity]').forEach(x=>x.classList.remove('active'));b.classList.add('active');activityMode=b.dataset.activity;loadActivity()}));$('#activityRefresh').addEventListener('click',loadActivity);$('#adminForm').addEventListener('submit',saveAdmin);
$('#licenseModal').addEventListener('click',e=>{if(e.target===$('#licenseModal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#licenseModal').classList.contains('open'))closeModal()});

(async()=>{if(!token)return;try{const j=await api('me');profile=j.profile;showApp()}catch{forceLogout()}})();