import {esc,ENDPOINT} from './control-shared.js';
import {ORIGIN,EXISTING_VERIFICATION,EXISTING_ADS,pageUrl,httpUrl,normalizeSEO,auditDocument} from './seo-shared.js';
const memory=new Map();
const field=(name,label,value='',area=false)=>`<label>${esc(label)}${area?`<textarea name="${name}" rows="4">${esc(value)}</textarea>`:`<input name="${name}" value="${esc(value)}">`}</label>`;
const message=(node,text)=>{if(node)node.textContent=text;};
const fmt=v=>v==null?'ยังไม่มีข้อมูล':Number(v).toLocaleString('th-TH',{maximumFractionDigits:2});
function reviewSummary(value){const s=value.seo||{};const rows=[['Title',value.seoTitle],['Description',value.description],['ภาพแชร์',value.image],['Keyword',s.keywords],['H1',s.h1],['H2',s.h2],['เนื้อหา',s.text],['FAQ',(s.faq||[]).map(x=>x.question+' — '+x.answer).join('\n')],['ALT',(s.images||[]).map(x=>x.src+' → '+x.alt).join('\n')],['ลิงก์',(s.links||[]).map(x=>x.title+' → '+x.url).join('\n')],['Canonical',s.canonical||'ใช้ URL ของหน้า'],['อนุญาตค้นหา',s.noindex?'ไม่อนุญาต (noindex)':'อนุญาต']];return rows.map(([label,text])=>`<h4>${label}</h4><p style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(text||'ใช้ค่าเดิม / ไม่ได้กำหนด')}</p>`).join('');}
export function mountSEO(ctx){
 const {root,content,pageIndex,call,change,toast,save,preview}=ctx;
 const p=content.pages[pageIndex]||content.pages[0],s=normalizeSEO(p.seo),m=content.marketing||{};
 const state=memory.get(p.slug)||{audit:null,search:null,performance:null};memory.set(p.slug,state);
 const $=selector=>root.querySelector(selector);
 const valid=()=>root.querySelector('#seo-workspace')?.dataset.slug===p.slug;
 const error=e=>toast(e.message||String(e));
 async function remote(action,data={}){const r=await fetch(ENDPOINT.replace('wellsound24-control','wellsound24-seo'),{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+ctx.token},body:JSON.stringify({action,slug:p.slug,...data}),signal:AbortSignal.timeout(70000)});const d=await r.json();if(!r.ok)throw new Error(d.error||'เชื่อมต่อไม่สำเร็จ');return d;}
 root.innerHTML=`<div id="seo-workspace" data-slug="${esc(p.slug)}">
 <div class="panel"><span class="eyebrow">SEO / การตลาด · 14 งานในหน้าเดียว</span><h2>ให้ลูกค้าค้นพบ Wellsound24</h2><p>ตรวจเว็บจริง → รับข้อเสนอ → ตรวจตัวอย่าง → อนุมัติเป็นร่าง → เผยแพร่</p><label>หน้าที่ต้องการดูแล<select id="seo-page">${content.pages.map((x,i)=>`<option value="${i}" ${i===pageIndex?'selected':''}>${esc(x.title)}</option>`).join('')}</select></label><a href="${esc(pageUrl(p))}" target="_blank" rel="noopener">เปิดหน้า production ↗</a><p id="seo-status" role="status">กำลังตรวจการเชื่อมต่อ…</p></div>
 <div class="panel"><h2>AI SEO · Keyword และข้อเสนอรายหน้า</h2><p>วิเคราะห์ชื่อหน้า เนื้อหา FAQ, Local SEO กทม./ปริมณฑล, ALT และลิงก์ภายใน ข้อเสนอจะยังไม่เปลี่ยนข้อมูลจนกดอนุมัติ</p><div class="actions"><button id="seo-ai" class="primary">ให้ AI วิเคราะห์และแนะนำ</button><button id="seo-ai-results">AI วิเคราะห์ผลเพื่อปรับปรุงต่อเนื่อง</button></div><p id="ai-status" role="status"></p><div id="ai-reasons"></div></div>
 <div class="panel"><h2>SEO รายหน้า / ตรวจและอนุมัติ</h2><form id="seo-editor">${field('seoTitle','SEO Title',p.seoTitle)}${field('description','Meta Description',p.description,true)}${field('keywords','Keyword ที่ติดตาม (คั่นด้วยจุลภาค สูงสุด 20 คำ)',s.keywords)}${field('h1','H1 หลัก (เว้นว่างเพื่อใช้เนื้อหาเดิม)',s.h1)}${field('h2','H2 ของส่วนเนื้อหา SEO',s.h2)}${field('text','เนื้อหา SEO / Local SEO ที่ยืนยันได้จริง',s.text,true)}${field('faq','FAQ: คำถาม | คำตอบ (หนึ่งคู่ต่อบรรทัด)',s.faq.map(x=>x.question+' | '+x.answer).join('\n'),true)}
 <h3>ภาพแชร์</h3>${field('image','URL ภาพแชร์',p.image)}<div class="actions"><button type="button" id="seo-media">เลือกรูปจากคลัง</button><label>อัปโหลดรูป<input type="file" id="seo-upload" accept="image/jpeg,image/png,image/webp,image/gif"></label></div><div id="seo-media-list" class="media-grid"></div>
 <h3>Image SEO / Internal links</h3><p class="muted">ALT ใช้กับรูป URL เดียวกันในหน้านี้ ส่วนชื่อไฟล์เป็นคำแนะนำสำหรับการอัปโหลดครั้งใหม่ เพื่อรักษาลิงก์รูปเดิม</p><div id="seo-images"></div><p>ลิงก์ที่แนะนำจากหน้าที่มีอยู่: ${content.pages.filter(x=>x.slug!==p.slug).map(x=>esc(x.title)).join(' · ')||'ยังมีหน้าเดียว ใช้ลิงก์ไปยังส่วนบริการหรือผลงานได้'}</p>${field('links','ลิงก์ภายใน: ชื่อลิงก์ | URL (หนึ่งรายการต่อบรรทัด)',s.links.map(x=>x.title+' | '+x.url).join('\n'),true)}
 <details><summary>Technical SEO รายหน้า</summary>${field('canonical','Canonical URL (เว้นว่างเพื่อใช้ URL ของหน้านี้)',p.seo?.canonical||'')}<label><input name="noindex" type="checkbox" ${s.noindex?'checked':''}> ไม่ให้แสดงหน้านี้ในผลค้นหา (noindex)</label><p>Schema WebPage และ FAQ สร้างจากเนื้อหาที่อนุมัติ ส่วน sitemap อัปเดตจากหน้าที่เผยแพร่และอนุญาต index</p></details>
 <button class="primary">ตรวจข้อเสนอก่อนอนุมัติ</button></form><div id="seo-review"></div></div>
 <div class="panel"><h2>Technical SEO / SEO Audit อัตโนมัติ</h2><p>ตรวจ HTML ที่ production ส่งจริง: Title, H1, ALT, canonical, schema, indexing directive และลิงก์ภายใน พร้อมตรวจ Title ซ้ำทุกหน้า</p><div class="actions"><button id="seo-audit">ตรวจทุกหน้าใหม่</button><button id="seo-performance">ตรวจ Core Web Vitals / ความเร็ว</button><a href="/sitemap.xml" target="_blank">Sitemap ↗</a><a href="/robots.txt" target="_blank">robots.txt ↗</a></div><div id="seo-audit-result" role="status"></div><div id="seo-performance-result"></div></div>
 <div class="panel"><h2>Google Verification / Analytics / Meta Pixel</h2><form id="seo-marketing">${field('verification','Google Site Verification (ค่า content ของ meta tag)',m.verification??EXISTING_VERIFICATION)}${field('searchConsoleProperty','Search Console property URL',m.searchConsoleProperty||ORIGIN+'/')}${field('ga','Google Analytics Measurement ID (G-...)',m.ga)}<p>GA4 วัดผู้เข้าชมและพฤติกรรม โหลดหลังผู้ชมยินยอม</p>${field('pixel','Meta Pixel ID (ตัวเลข)',m.pixel)}<p>Meta Pixel ใช้วัดผลโฆษณา Meta โหลดหลังผู้ชมยินยอม</p><p>Google Ads tag เดิม: <strong>${EXISTING_ADS}</strong> เป็นรหัสโฆษณา ไม่ใช่ GA4 Measurement ID</p><button>ตรวจและเก็บค่าการเชื่อมต่อเป็นร่าง</button></form><button id="seo-install-check">ตรวจค่าที่ติดตั้งบน production</button><div id="seo-install-result"></div></div>
 <div class="panel"><h2>Search Console / Keyword rank tracking</h2><p>1. บันทึกและเผยแพร่ verification → 2. ยืนยัน property ใน Google → 3. ให้สิทธิ์ API → 4. ตรวจการเชื่อมต่อและดึงรายงาน</p><a href="https://search.google.com/search-console" target="_blank" rel="noopener">เปิด Google Search Console ↗</a><p>อันดับคือ Average position จากการแสดงผลจริงของ Google เปรียบเทียบช่วง 28 วันล่าสุดที่ข้อมูลสมบูรณ์กับ 28 วันก่อนหน้า ไม่ใช่อันดับแบบตรวจสด</p><div class="actions"><button id="seo-gsc">ตรวจการเชื่อมต่อ / ดึงรายงาน</button><button id="seo-index">ตรวจ Google indexing ของหน้านี้</button></div><div id="seo-gsc-result" role="status"></div><div id="seo-index-result"></div><details><summary>การเชื่อม API ที่ยังขาด</summary><p>ผู้ดูแลระบบตั้งค่า Secrets ใน Supabase: OPENAI_API_KEY สำหรับ AI; GOOGLE_SERVICE_ACCOUNT_JSON พร้อมสิทธิ์อ่าน property หรือ GOOGLE_CLIENT_ID + GOOGLE_CLIENT_SECRET + GOOGLE_REFRESH_TOKEN สำหรับ Search Console; PAGESPEED_API_KEY หาก Google จำกัดโควตา ห้ามวาง secret ในช่อง SEO หรือโค้ดหน้าเว็บ</p></details></div></div>`;
 let draftImages=s.images.map(x=>({...x}));
 function renderImages(){ $('#seo-images').innerHTML=draftImages.length?draftImages.map((x,i)=>`<div class="seo-image-row"><p>${esc(x.src)}</p>${field('alt-'+i,'ALT',x.alt)}<small>ชื่อไฟล์แนะนำ: ${esc(x.filename||'ยังไม่มีข้อเสนอ')}</small></div>`).join(''):'<p class="muted">ตรวจ Audit หรือให้ AI วิเคราะห์เพื่อแสดงรูปของหน้านี้</p>';}
 renderImages();
 $('#seo-page').onchange=e=>ctx.selectPage(+e.target.value);
 const form=$('#seo-editor');let formDirty=false;
 form.oninput=()=>{formDirty=true;$('#seo-review').innerHTML='';};
 function readForm(){const d=Object.fromEntries(new FormData(form));const pairs=v=>String(v||'').split('\n').filter(x=>x.trim()).map(line=>{const i=line.indexOf('|');if(i<1)throw new Error('ใช้รูปแบบ ข้อความ | ข้อความ โดยคั่นด้วย |');return [line.slice(0,i).trim(),line.slice(i+1).trim()];});
  const canonical=String(d.canonical||'').trim();if(canonical&&(!/^https?:\/\//.test(canonical)||!httpUrl(canonical)))throw new Error('Canonical ต้องเป็น URL http หรือ https');
  if(d.image&&!httpUrl(d.image))throw new Error('URL ภาพไม่ถูกต้อง');
  const links=pairs(d.links).map(([title,url])=>({title,url}));if(links.some(x=>!httpUrl(x.url).startsWith(ORIGIN+'/')))throw new Error('ลิงก์ภายในต้องเป็น URL ของ Wellsound24');
  return {seoTitle:String(d.seoTitle).trim().slice(0,250),description:String(d.description).trim().slice(0,1000),image:d.image?httpUrl(d.image):'',seo:{...normalizeSEO({...d,faq:pairs(d.faq).map(([question,answer])=>({question,answer})),links,images:draftImages.map((x,i)=>({...x,alt:d['alt-'+i]||''})),noindex:d.noindex==='on'}),canonical}};
 }
 form.onsubmit=e=>{e.preventDefault();try{const next=readForm();if(!next.seoTitle||!next.description)throw new Error('กรอก Title และ Description ก่อน');const before={seoTitle:p.seoTitle,description:p.description,image:p.image,seo:p.seo||{}};$('#seo-review').innerHTML=`<h3>เปรียบเทียบก่อนอนุมัติ</h3><div class="seo-diff"><div><h4>เดิม</h4>${reviewSummary(before)}</div><div><h4>ข้อเสนอ</h4>${reviewSummary(next)}</div></div><p>อนุมัติจะเปลี่ยนเฉพาะร่างของหน้านี้ จากนั้นบันทึกร่างและตรวจตัวอย่างก่อนกดเผยแพร่เว็บ</p><div class="actions"><button id="seo-approve" class="primary">อนุมัติใช้กับร่างหน้านี้</button><button id="seo-reject">ยกเลิกข้อเสนอ</button></div>`;
 $('#seo-approve').onclick=()=>{Object.assign(p,next);change();formDirty=false;$('#seo-review').innerHTML='<p>อนุมัติเป็นร่างแล้ว ยังไม่เปลี่ยนเว็บจริง</p><div class="actions"><button id="seo-save-draft">บันทึกร่าง</button><button id="seo-preview">ดูตัวอย่างหน้าเว็บ</button></div>';$('#seo-save-draft').onclick=()=>save();$('#seo-preview').onclick=preview;toast('อนุมัติ SEO เป็นร่างแล้ว');};$('#seo-reject').onclick=()=>{$('#seo-review').innerHTML='';};}catch(e){error(e);}};
 async function suggest(withResults){const button=withResults?$('#seo-ai-results'):$('#seo-ai');button.disabled=true;message($('#ai-status'),'กำลังวิเคราะห์…');try{if(withResults&&!state.search)throw new Error('ดึงรายงาน Search Console จริงก่อน เพื่อให้ AI วิเคราะห์ผล');const d=await remote('suggest',{page:{...p,seo:readForm().seo},audit:state.audit,performance:state.performance,searchConsole:withResults?state.search:null});if(!valid())return;if(formDirty&&!confirm('แทนที่ข้อความในฟอร์มที่ยังไม่อนุมัติด้วยข้อเสนอ AI หรือไม่?'))return;const a=d.proposal||{},n=normalizeSEO({...a,canonical:p.seo?.canonical,noindex:p.seo?.noindex});for(const key of ['seoTitle','description'])if(typeof a[key]==='string')form.elements.namedItem(key).value=a[key];for(const key of ['keywords','h1','h2','text'])form.elements.namedItem(key).value=n[key];form.elements.namedItem('faq').value=n.faq.map(x=>x.question+' | '+x.answer).join('\n');form.elements.namedItem('links').value=n.links.map(x=>x.title+' | '+x.url).join('\n');draftImages=n.images;renderImages();formDirty=true;$('#seo-review').innerHTML='';$('#ai-reasons').innerHTML='<ul>'+(Array.isArray(a.reasons)?a.reasons:[]).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';message($('#ai-status'),'ข้อเสนอจาก AI อยู่ในฟอร์มแล้ว กรุณาตรวจและอนุมัติ');}catch(e){message($('#ai-status'),e.message);}finally{button.disabled=false;}}
 $('#seo-ai').onclick=()=>suggest(false);$('#seo-ai-results').onclick=()=>suggest(true);
 $('#seo-media').onclick=async()=>{try{const {items}=await call('media');if(!valid())return;const images=items.filter(x=>/\.(jpg|png|webp|gif)$/i.test(x.name));$('#seo-media-list').innerHTML=images.map((x,i)=>`<button type="button" data-image="${i}"><img src="${esc(x.url)}" alt="${esc(x.name)}" loading="lazy"><span>ใช้รูปนี้</span></button>`).join('')||'<p>ยังไม่มีรูปในคลัง</p>';$('#seo-media-list').querySelectorAll('[data-image]').forEach(b=>b.onclick=()=>{form.elements.namedItem('image').value=images[+b.dataset.image].url;formDirty=true;$('#seo-review').innerHTML='';$('#seo-media-list').innerHTML='';});}catch(e){error(e);}};
 $('#seo-upload').onchange=async e=>{const file=e.target.files[0];if(!file)return;e.target.disabled=true;try{const d=await call('upload_url',{type:file.type,size:file.size});const r=await fetch(d.signedUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!r.ok)throw new Error('อัปโหลดไม่สำเร็จ');if(valid()){form.elements.namedItem('image').value=d.url;formDirty=true;$('#seo-review').innerHTML='';toast('อัปโหลดและสร้าง URL ภาพแล้ว');}}catch(e){error(e);}finally{e.target.disabled=false;}};
 $('#seo-marketing').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));for(const k in d)d[k]=d[k].trim();if(d.ga&&!/^G-[A-Z0-9]+$/.test(d.ga)||d.pixel&&!/^\d{5,30}$/.test(d.pixel))return toast('รูปแบบ GA หรือ Meta Pixel ID ไม่ถูกต้อง');if(d.verification&&!/^[A-Za-z0-9_-]{10,200}$/.test(d.verification))return toast('กรอกเฉพาะค่า verification ไม่ใช่ meta tag ทั้งบรรทัด');if(d.searchConsoleProperty!==ORIGIN+'/')return toast('ใช้ property URL ของ production เดิม: '+ORIGIN+'/');if(!confirm('อนุมัติค่าการเชื่อมต่อเหล่านี้เป็นร่าง? จะใช้จริงเมื่อเผยแพร่เว็บ'))return;content.marketing={...content.marketing,...d};change();toast('เก็บค่าการเชื่อมต่อเป็นร่างแล้ว กรุณาบันทึกและเผยแพร่');};
 async function installCheck(){message($('#seo-install-result'),'กำลังตรวจ HTML production…');try{const r=await fetch('/?page='+encodeURIComponent(p.slug),{cache:'no-store'});if(!r.ok)throw new Error('หน้าเว็บตอบ HTTP '+r.status);const html=await r.text(),doc=new DOMParser().parseFromString(html,'text/html');const published=JSON.parse(doc.querySelector('#w24-published')?.textContent||'null');const actual=published?.marketing||{};const verification=doc.querySelector('meta[name="google-site-verification"]')?.content;const expected=content.marketing||{};message($('#seo-install-result'),`Verification: ${verification=== (expected.verification??EXISTING_VERIFICATION)?'ตรงกับร่าง':'ยังไม่ตรงกับร่าง'} · GA4: ${actual.ga||'ยังไม่ได้ตั้งค่า'} ${actual.ga===expected.ga?'(ตรงกับร่าง)':'(ยังไม่ตรงกับร่าง)'} · Pixel: ${actual.pixel||'ยังไม่ได้ตั้งค่า'} ${actual.pixel===expected.pixel?'(ตรงกับร่าง)':'(ยังไม่ตรงกับร่าง)'} · Google Ads: ${html.includes(EXISTING_ADS)?'พบ tag เดิม':'ไม่พบ'} · GA/Pixel ที่มีค่าถูกต้องพร้อมโหลดหลังผู้ชมยินยอม สถานะนี้ยังไม่ยืนยันว่าบัญชีปลายทางรับ event แล้ว`);}catch(e){message($('#seo-install-result'),e.message);}}
 $('#seo-install-check').onclick=installCheck;
 async function audit(){const button=$('#seo-audit');button.disabled=true;const result=$('#seo-audit-result');message(result,'กำลังตรวจหน้า production…');try{const reports=[];const publicData=await call('public');const publishedPages=publicData.published?.pages||[];for(const page of publishedPages){const start=performance.now(),r=await fetch('/?page='+encodeURIComponent(page.slug),{cache:'no-store'});const doc=new DOMParser().parseFromString(await r.text(),'text/html');const report=auditDocument(doc,pageUrl(page));report.responseMs=Math.round(performance.now()-start);report.checks.unshift({name:'HTTP',status:r.ok?'pass':'warn',detail:String(r.status)});reports.push(report);if(page.slug===p.slug){state.audit=report;if(!draftImages.length&&!formDirty){draftImages=report.images;renderImages();}}}
 const titles=new Map();for(const x of reports){titles.set(x.title,(titles.get(x.title)||0)+1);}for(const x of reports)x.checks.push({name:'Title ซ้ำ',status:titles.get(x.title)>1?'warn':'pass',detail:titles.get(x.title)>1?'พบชื่อซ้ำหลายหน้า':'ไม่ซ้ำ'});
 const links=[...new Set(reports.flatMap(x=>x.links).map(x=>httpUrl(x)).filter(x=>x.startsWith(ORIGIN+'/')))].slice(0,40);const broken=[];for(const url of links){try{const r=await fetch(url.replace(ORIGIN,''),{method:'HEAD',redirect:'follow',signal:AbortSignal.timeout(8000)});if(!r.ok)broken.push(url+' · HTTP '+r.status);}catch{broken.push(url+' · ตรวจไม่สำเร็จ');}}
 if(!valid())return;result.innerHTML=`<p>ตรวจเมื่อ ${new Date().toLocaleString('th-TH')} · ${reports.length} หน้า · ลิงก์ในเว็บ ${links.length} รายการ (สูงสุด 40 ต่อรอบ; ไม่ตรวจลิงก์ภายนอก)</p>${reports.map(x=>`<details open><summary>${esc(x.title)} · ตอบกลับ ${x.responseMs} ms</summary><ul>${x.checks.map(y=>`<li>${y.status==='pass'?'✓':'⚠'} ${esc(y.name)} — ${esc(y.detail)}</li>`).join('')}</ul></details>`).join('')}<p>ลิงก์เสีย/ตรวจไม่ได้: ${broken.length?broken.map(esc).join('<br>'):'ไม่พบในลิงก์ที่ตรวจ'}</p><p class="muted">เวลาตอบกลับรวมเครือข่าย ไม่ใช่ Core Web Vitals ใช้ปุ่มตรวจความเร็วเพื่อดึงข้อมูล Google</p>`;
 }catch(e){message(result,e.message);}finally{button.disabled=false;}}
 $('#seo-audit').onclick=audit;
 $('#seo-performance').onclick=async e=>{e.target.disabled=true;message($('#seo-performance-result'),'กำลังตรวจด้วย Google PageSpeed Insights…');try{state.performance=await remote('performance');if(valid())$('#seo-performance-result').innerHTML=`<p>คะแนนทดสอบมือถือ: ${state.performance.score==null?'ไม่มีข้อมูล':Math.round(state.performance.score*100)} / 100</p><p>Lab: LCP ${esc(state.performance.lab.lcp||'ไม่มีข้อมูล')} · CLS ${esc(state.performance.lab.cls||'ไม่มีข้อมูล')} · TBT ${esc(state.performance.lab.tbt||'ไม่มีข้อมูล')}</p><p>ข้อมูลผู้ใช้จริง (CrUX): ${esc(state.performance.field?.overall_category||'ข้อมูลไม่เพียงพอ')}</p><pre>${esc(JSON.stringify(state.performance.field?.metrics||{},null,2))}</pre>`;}catch(e){message($('#seo-performance-result'),e.message);}finally{e.target.disabled=false;}};
 $('#seo-gsc').onclick=async e=>{e.target.disabled=true;message($('#seo-gsc-result'),'กำลังตรวจสิทธิ์และดึงข้อมูลจริง…');try{const keywords=(p.seo?.keywords||'').split(',').map(x=>x.trim()).filter(Boolean);state.search=await remote('search_console',{keywords});if(!valid())return;const d=state.search,t=d.totals;$('#seo-gsc-result').innerHTML=`<p>เชื่อมต่อแล้ว · ${esc(d.start)} ถึง ${esc(d.end)} · ${esc(d.source)}</p><div class="stats">${[['Clicks',t?.clicks],['Impressions',t?.impressions],['CTR (%)',t==null?null:t.ctr*100],['Average position',t?.position]].map(([k,v])=>`<div class="stat"><span>${k}</span><strong>${fmt(v)}</strong></div>`).join('')}</div><h3>คำค้น (สูงสุด 1,000 แถวจาก Google)</h3><div class="seo-table"><table><thead><tr><th>Query</th><th>Clicks</th><th>Impressions</th><th>CTR %</th><th>Position</th></tr></thead><tbody>${d.queries.map(x=>`<tr><td>${esc(x.keys[0])}</td><td>${fmt(x.clicks)}</td><td>${fmt(x.impressions)}</td><td>${fmt(x.ctr*100)}</td><td>${fmt(x.position)}</td></tr>`).join('')}</tbody></table></div>${!d.queries.length?'<p>Google ยังไม่มีข้อมูลคำค้นในช่วงนี้</p>':''}<h3>Keyword ที่ติดตาม</h3><div class="seo-table"><table><tr><th>คำค้น</th><th>อันดับเฉลี่ยปัจจุบัน</th><th>ช่วงก่อน</th><th>เปลี่ยนแปลง (บวก = ดีขึ้น)</th></tr>${d.ranks.map(x=>`<tr><td>${esc(x.keyword)}</td><td>${fmt(x.current?.position)}</td><td>${fmt(x.previous?.position)}</td><td>${fmt(x.current&&x.previous?x.previous.position-x.current.position:null)}</td></tr>`).join('')}</table></div><details><summary>แนวโน้มรายวัน</summary><div class="seo-table"><table><tr><th>วันที่</th><th>Clicks</th><th>Impressions</th><th>Position</th></tr>${d.trend.map(x=>`<tr><td>${esc(x.keys[0])}</td><td>${fmt(x.clicks)}</td><td>${fmt(x.impressions)}</td><td>${fmt(x.position)}</td></tr>`).join('')}</table></div></details>`;}catch(e){message($('#seo-gsc-result'),e.message);}finally{e.target.disabled=false;}};
 $('#seo-index').onclick=async e=>{e.target.disabled=true;message($('#seo-index-result'),'กำลังตรวจ Google URL Inspection…');try{const d=await remote('inspect');const x=d.inspectionResult?.indexStatusResult;message($('#seo-index-result'),x?`Google: ${x.verdict} · ${x.coverageState||''} · Last crawl: ${x.lastCrawlTime||'ไม่มีข้อมูล'} · Google canonical: ${x.googleCanonical||'ไม่มีข้อมูล'}`:'ไม่มีข้อมูล Inspection');}catch(e){message($('#seo-index-result'),e.message);}finally{e.target.disabled=false;}};
 remote('status').then(d=>{if(valid())message($('#seo-status'),`AI: ${d.ai?'มี API key พร้อมตรวจใช้งาน':'รอ OPENAI_API_KEY'} · Search Console API: ${d.searchConsole?'มี credential พร้อมตรวจสิทธิ์':'รอ credential และสิทธิ์ property'} · ค่า verification ของเว็บไม่ใช่ credential สำหรับอ่านรายงาน`);}).catch(e=>message($('#seo-status'),e.message));
 audit();installCheck();
}
