import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import vm from 'node:vm';
const source=stripTypeScriptTypes(readFileSync('supabase/functions/wellsound24-seo/index.ts','utf8').replace(/^import .*\n/,'').replace('export async function handler','async function handler'));
function fixture({authStatus=200,secrets={},allowed=true}={}){const calls=[];let handler;const context={Deno:{env:{get:k=>secrets[k]||''},serve:f=>handler=f},createClient:()=>({rpc:async()=>({data:allowed})}),Response,Request,URLSearchParams,TextEncoder,Uint8Array,AbortSignal,crypto:globalThis.crypto,btoa,atob,fetch:async(url,options)=>{calls.push({url,options});if(url.endsWith('wellsound24-control'))return new Response(JSON.stringify({profile:{id:'test'},state:{draft:{pages:[{slug:'home'}]}}}),{status:authStatus});throw new Error('Unexpected external call');}};vm.runInNewContext(source,context);return {handler,calls};}
test('SEO API rejects unauthenticated requests before reading data or provider calls',async()=>{const {handler,calls}=fixture();const r=await handler(new Request('https://test',{method:'POST',body:'{"action":"status"}'}));assert.equal(r.status,401);assert.equal(calls.length,0);});
test('SEO API rechecks current session and permissions on each request',async()=>{const {handler,calls}=fixture({authStatus:403});const r=await handler(new Request('https://test',{method:'POST',headers:{Authorization:'Bearer test'},body:'{"action":"suggest"}'}));assert.equal(r.status,403);assert.equal(calls.length,1);});
test('status exposes booleans not secrets; missing AI returns actionable failure',async()=>{const f=fixture({secrets:{OPENAI_API_KEY:'not-a-real-key'}});let r=await f.handler(new Request('https://test',{method:'POST',headers:{Authorization:'Bearer test'},body:'{"action":"status"}'}));const text=await r.text();assert.ok(!text.includes('not-a-real-key'));assert.equal(JSON.parse(text).ai,true);const g=fixture();r=await g.handler(new Request('https://test',{method:'POST',headers:{Authorization:'Bearer test'},body:'{"action":"suggest","slug":"home"}'}));assert.equal(r.status,503);assert.equal((await r.json()).missing,'OPENAI_API_KEY');assert.equal(g.calls.length,1);});
test('missing Google credentials yields failure, never fabricated metrics',async()=>{const {handler}=fixture();const r=await handler(new Request('https://test',{method:'POST',headers:{Authorization:'Bearer test'},body:'{"action":"search_console","slug":"home"}'}));assert.equal(r.status,502);const d=await r.json();assert.ok(d.error.includes('GOOGLE_SERVICE_ACCOUNT_JSON'));assert.equal(d.totals,undefined);});
test('rate limit prevents provider spending',async()=>{const {handler,calls}=fixture({allowed:false,secrets:{OPENAI_API_KEY:'not-a-real-key'}});const r=await handler(new Request('https://test',{method:'POST',headers:{Authorization:'Bearer test'},body:'{"action":"suggest","slug":"home"}'}));assert.equal(r.status,429);assert.equal(calls.length,1);});
