plugins {
    id 'com.android.application'
}

android {
    namespace 'com.wellhonda.obdpro'
    compileSdk 35

    defaultConfig {
        applicationId "com.wellhonda.obdpro.standard2"
        minSdk 26
        targetSdk 35
        versionCode 21
        versionName "2.0-standard2-mobile-r2"
    }
}

dependencies {
}
