plugins {
    id 'com.android.application'
}

android {
    namespace 'com.wellhonda.obdpro'
    compileSdk 35

    defaultConfig {
        applicationId "com.wellhonda.obdpro.standard2.r3"
        minSdk 21
        targetSdk 34
        versionCode 22
        versionName "2.0-standard2-mobile-r3"
    }
}

dependencies {
}
