package com.wellsound.autofeedback;

import android.app.*;import android.os.*;import android.graphics.*;import android.view.*;import android.widget.*;import java.net.*;import java.nio.*;import java.nio.charset.StandardCharsets;import java.io.*;import java.util.*;import java.util.concurrent.*;

public class MainActivity extends Activity{
  EditText ip; TextView status,candidate,bankText,log; Spinner target,mode; CheckBox arm; Spectrum spectrum; DatagramSocket sock; volatile boolean running=false,connected=false; long lastRx=0,candStart=0; int candKey=-1; float[] rta=new float[100]; ArrayList<Notch> bank=new ArrayList<>(); HashMap<String,Object> snap=new HashMap<>(); ExecutorService net=Executors.newSingleThreadExecutor();
  final int[] F={20,21,22,24,26,28,30,32,34,36,39,42,45,48,52,55,59,63,68,73,78,84,90,96,103,110,118,127,136,146,156,167,179,192,206,221,237,254,272,292,313,335,359,385,412,442,474,508,544,583,625,670,718,769,825,884,947,1020,1090,1170,1250,1340,1440,1540,1650,1770,1890,2030,2180,2330,2500,2680,2870,3080,3300,3540,3790,4060,4350,4670,5000,5360,5740,6160,6600,7070,7580,8120,8710,9330,10000,10720,11490,12310,13200,14140,15160,16250,17410,18660};
  static class Notch{int band,f,conf;float cut,q;Notch(int b,int ff,float c,float qq,int co){band=b;f=ff;cut=c;q=qq;conf=co;}}
  public void onCreate(Bundle b){super.onCreate(b);ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,28,28,28);root.setBackgroundColor(Color.rgb(8,11,16));sv.addView(root);setContentView(sv);
    TextView title=t("Well Auto Feedback • M32R",24,true);root.addView(title);status=t("DISCONNECTED",14,false);status.setTextColor(Color.LTGRAY);root.addView(status);
    ip=new EditText(this);ip.setText("192.168.1.100");ip.setTextColor(Color.WHITE);ip.setHintTextColor(Color.GRAY);ip.setHint("M32R IP");root.addView(ip,lp());
    Button con=btn("CONNECT M32R");root.addView(con,lp());
    ArrayList<String> tg=new ArrayList<>();tg.add("Main LR");for(int i=1;i<=16;i++)tg.add(String.format(Locale.US,"Bus %02d",i));target=new Spinner(this);target.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,tg));root.addView(target,lp());
    mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"MONITOR","ASSIST","AUTO","RING OUT"}));mode.setSelection(1);root.addView(mode,lp());
    arm=new CheckBox(this);arm.setText("ARM AUTO CUT");arm.setTextColor(Color.WHITE);root.addView(arm,lp());
    spectrum=new Spectrum(this);root.addView(spectrum,new LinearLayout.LayoutParams(-1,520));
    candidate=t("Candidate: —",18,true);root.addView(candidate);bankText=t("Auto Notches: 0 / 6",16,false);root.addView(bankText);
    Button undo=btn("UNDO LAST CUT"),restore=btn("RESTORE ORIGINAL EQ");root.addView(undo,lp());root.addView(restore,lp());log=t("Ready\nAUTO CUT is disarmed by default.",12,false);log.setTextColor(Color.LTGRAY);root.addView(log,lp());
    con.setOnClickListener(v->connect());undo.setOnClickListener(v->undo());restore.setOnClickListener(v->restore());
    target.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){if(sock!=null){bank.clear();configure();snapshot();refresh();}}public void onNothingSelected(android.widget.AdapterView<?> p){}});
  }
  TextView t(String s,int size,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(size);v.setPadding(0,10,0,10);if(bold)v.setTypeface(null,1);return v;} Button btn(String s){Button b=new Button(this);b.setText(s);return b;} LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,8,0,8);return p;}
  String base(){String s=(String)target.getSelectedItem();if(s==null||s.equals("Main LR"))return "/main/st";return "/bus/"+s.substring(4);} int source(){String s=(String)target.getSelectedItem();if(s==null||s.equals("Main LR"))return 72;return 49+Integer.parseInt(s.substring(4));}
  void connect(){stop();net.execute(()->{try{sock=new DatagramSocket();sock.setSoTimeout(500);running=true;sendNow("/info");configureNow();snapshotNow();new Thread(this::rx).start();new Thread(this::keep).start();ui("Connecting to "+ip.getText().toString()+":10023");}catch(Exception e){ui(e.toString());}});}
  void stop(){running=false;if(sock!=null){sock.close();sock=null;}connected=false;}
  void send(String a,Object...v){net.execute(()->{try{sendNow(a,v);}catch(Exception e){ui("Send: "+e.getMessage());}});} void sendNow(String a,Object...v)throws Exception{if(sock==null)return;byte[] d=osc(a,v);InetAddress h=InetAddress.getByName(ip.getText().toString().trim());sock.send(new DatagramPacket(d,d.length,h,10023));}
  void configure(){send("/-prefs/rta/source",source());send("/-prefs/rta/pos",0);send("/-prefs/rta/det",1);} void configureNow()throws Exception{sendNow("/-prefs/rta/source",source());sendNow("/-prefs/rta/pos",0);sendNow("/-prefs/rta/det",1);} void snapshot(){snap.clear();send(base()+"/eq/on");for(int i=1;i<=6;i++)for(String p:new String[]{"type","f","g","q"})send(base()+"/eq/"+i+"/"+p);} void snapshotNow()throws Exception{snap.clear();sendNow(base()+"/eq/on");for(int i=1;i<=6;i++)for(String p:new String[]{"type","f","g","q"})sendNow(base()+"/eq/"+i+"/"+p);}
  void keep(){long sub=0;while(running){send("/xremote");if(System.currentTimeMillis()-sub>7000){configure();send("/meters","/meters/15",1);sub=System.currentTimeMillis();}try{Thread.sleep(1000);}catch(Exception e){}}}
  void rx(){byte[] buf=new byte[65535];while(running){try{DatagramPacket p=new DatagramPacket(buf,buf.length);sock.receive(p);lastRx=System.currentTimeMillis();if(!connected){connected=true;runOnUiThread(()->status.setText("M32R CONNECTED"));ui("OSC response received");}parse(Arrays.copyOf(p.getData(),p.getLength()));}catch(SocketTimeoutException e){if(System.currentTimeMillis()-lastRx>4000)runOnUiThread(()->status.setText("DISCONNECTED"));}catch(Exception e){if(running)ui("RX: "+e.getMessage());}}}
  void parse(byte[] d){try{int[] o={0};String a=rs(d,o),tags=rs(d,o);if(a.equals("/meters/15")&&tags.contains("b")){int n=ByteBuffer.wrap(d,o[0],4).order(ByteOrder.BIG_ENDIAN).getInt();o[0]+=4;if(n>=200){byte[] b=Arrays.copyOfRange(d,o[0],Math.min(d.length,o[0]+n));decode(b);}return;}if((a.startsWith(base()+"/eq/")||a.equals(base()+"/eq/on"))&&tags.length()>1){Object val=null;if(tags.charAt(1)=='i')val=ByteBuffer.wrap(d,o[0],4).order(ByteOrder.BIG_ENDIAN).getInt();else if(tags.charAt(1)=='f')val=ByteBuffer.wrap(d,o[0],4).order(ByteOrder.BIG_ENDIAN).getFloat();if(val!=null&&!snap.containsKey(a))snap.put(a,val);}}catch(Exception e){}}
  void decode(byte[] b){try{int off=b.length>=204?4:0;if(b.length-off<200)return;ByteBuffer bb=ByteBuffer.wrap(b,off,200).order(ByteOrder.LITTLE_ENDIAN);for(int i=0;i<100;i++)rta[i]=bb.getShort()/256f;runOnUiThread(()->spectrum.setData(rta));detect();}catch(Exception e){}}
  void detect(){int bi=-1,bc=0;float be=0;for(int i=20;i<92;i++){if(rta[i]<-48||rta[i]<=rta[i-1]||rta[i]<=rta[i+1])continue;float sum=0;int n=0;for(int j=Math.max(0,i-4);j<Math.min(100,i+5);j++)if(Math.abs(j-i)>=2){sum+=rta[j];n++;}float ex=rta[i]-sum/n;if(ex<6.5)continue;float near=Math.max(rta[i-1],rta[i+1]);int c=(int)Math.max(0,Math.min(99,45+ex*4.8+Math.max(0,rta[i]-near)*2+Math.max(0,rta[i]+48)*.7));if(c>bc){bc=c;bi=i;be=ex;}}if(bi<0){candKey=-1;candStart=0;return;}int f=F[bi],conf=bc;float ex=be,db=rta[bi];int key=(int)Math.round(Math.log(f)/.035);if(key!=candKey){candKey=key;candStart=System.currentTimeMillis();return;}long held=System.currentTimeMillis()-candStart;runOnUiThread(()->candidate.setText("Candidate: "+f+" Hz • "+conf+"% • "+String.format(Locale.US,"%.1f dB",db)));if(held>=320&&conf>=92){boolean exists=false;for(Notch z:bank)if(Math.abs(Math.log(z.f/(double)f))<.055)exists=true;String m=(String)mode.getSelectedItem();if(!exists&&arm.isChecked()&&("AUTO".equals(m)||"RING OUT".equals(m)))notch(f,conf,ex);candKey=-1;candStart=0;}}
  synchronized void notch(int f,int conf,float ex){if(bank.size()>=6)return;int band=bank.size()+1;float cut=-Math.min(9f,Math.max(3f,Math.round(ex*.65f*4)/4f)),q=Math.min(10f,Math.max(6f,7f+ex*.25f));send(base()+"/eq/on",1);send(base()+"/eq/"+band+"/type",2);send(base()+"/eq/"+band+"/f",nlog(f,20,20000));send(base()+"/eq/"+band+"/g",nlin(cut,-15,15));send(base()+"/eq/"+band+"/q",nlog(q,10,.3f));bank.add(new Notch(band,f,cut,q,conf));ui("AUTO CUT EQ"+band+" "+f+"Hz "+cut+"dB Q"+q);runOnUiThread(this::refresh);}
  void undo(){if(bank.isEmpty())return;Notch n=bank.remove(bank.size()-1);for(String p:new String[]{"type","f","g","q"}){String a=base()+"/eq/"+n.band+"/"+p;Object v=snap.get(a);if(v!=null)send(a,v);}refresh();ui("Undo last cut");} void restore(){for(Map.Entry<String,Object> e:snap.entrySet())send(e.getKey(),e.getValue());bank.clear();refresh();ui("Original EQ restored");} void refresh(){bankText.setText("Auto Notches: "+bank.size()+" / 6");} float nlog(float v,float lo,float hi){return(float)(Math.log(v/lo)/Math.log(hi/lo));} float nlin(float v,float lo,float hi){return Math.max(0,Math.min(1,(v-lo)/(hi-lo)));} void ui(String s){runOnUiThread(()->log.setText(s+"\n"+log.getText()));}
  byte[] osc(String a,Object...args)throws Exception{ByteArrayOutputStream out=new ByteArrayOutputStream(),pay=new ByteArrayOutputStream();StringBuilder tags=new StringBuilder(",");for(Object x:args){if(x instanceof Integer){tags.append('i');pay.write(ByteBuffer.allocate(4).order(ByteOrder.BIG_ENDIAN).putInt((Integer)x).array());}else if(x instanceof Float){tags.append('f');pay.write(ByteBuffer.allocate(4).order(ByteOrder.BIG_ENDIAN).putFloat((Float)x).array());}else if(x instanceof String){tags.append('s');pay.write(ps((String)x));}}out.write(ps(a));out.write(ps(tags.toString()));out.write(pay.toByteArray());return out.toByteArray();} byte[] ps(String s)throws Exception{ByteArrayOutputStream o=new ByteArrayOutputStream();o.write(s.getBytes(StandardCharsets.UTF_8));o.write(0);while(o.size()%4!=0)o.write(0);return o.toByteArray();} String rs(byte[] d,int[] o){int i=o[0],e=i;while(e<d.length&&d[e]!=0)e++;String s=new String(d,i,e-i,StandardCharsets.UTF_8);o[0]=(e+4)&~3;return s;}
  protected void onDestroy(){super.onDestroy();stop();net.shutdownNow();}
  public static class Spectrum extends View{Paint p=new Paint(1);float[] v=new float[100];Spectrum(android.content.Context c){super(c);Arrays.fill(v,-90);setBackgroundColor(Color.rgb(5,8,12));}void setData(float[] x){v=x.clone();invalidate();}protected void onDraw(Canvas c){super.onDraw(c);p.setColor(Color.rgb(36,48,64));p.setStrokeWidth(1);for(int i=1;i<10;i++){float y=getHeight()*i/10f;c.drawLine(0,y,getWidth(),y,p);}p.setColor(Color.rgb(56,189,248));p.setStrokeWidth(3);Path path=new Path();for(int i=0;i<100;i++){float x=getWidth()*i/99f,db=Math.max(-90,Math.min(0,v[i])),y=(-db/90f)*(getHeight()-12)+6;if(i==0)path.moveTo(x,y);else path.lineTo(x,y);}c.drawPath(path,p);}}
}
