plugins {
    id 'com.android.application'
}

android {
    namespace 'com.well.rfscanner.v7'
    compileSdk 35

    defaultConfig {
        applicationId 'com.well.rfscanner.standard1'
        minSdk 26
        targetSdk 35
        versionCode 11
        versionName '1.1-standard-ui-signal-id'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
