plugins {
    id 'com.android.application'
}

android {
    namespace 'com.well.rfscanner.v7'
    compileSdk 35

    defaultConfig {
        applicationId 'com.well.rfscanner.v8'
        minSdk 26
        targetSdk 35
        versionCode 8
        versionName '0.8-real-usb'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
