from pathlib import Path

HTML=Path('well-assistant-pro-android/app/src/main/assets/index.html')
JAVA=Path('well-assistant-pro-android/app/src/main/java/com/wellsound/assistantpro/MainActivity.java')

s=HTML.read_text()
marker='REAL_M32_CONNECT_ONLY_V2'
if marker not in s:
    addon=r'''<!-- REAL_M32_CONNECT_ONLY_V2 -->
<style>
#testlab,.tabs button[data-p="testlab"]{display:none!important}
.m32ConnectPanel{border:1px solid #294759;background:linear-gradient(155deg,#0f1e2a,#0a151e);border-radius:18px;padding:14px;display:grid;gap:10px}.m32ConnectHead{display:flex;align-items:center;justify-content:space-between;gap:10px}.m32ConnectTitle{font-size:14px;font-weight:900}.m32ConnectState{display:flex;align-items:center;gap:7px;font-size:10px;font-weight:900;color:#8ea4b5}.m32ConnectDot{width:9px;height:9px;border-radius:50%;background:#6e7e8c;box-shadow:0 0 0 3px #172632}.m32ConnectState.connected{color:#77dbaa}.m32ConnectState.connected .m32ConnectDot{background:#48cf91;box-shadow:0 0 0 3px #153629}.m32ConnectState.connecting{color:#74c7ef}.m32ConnectState.connecting .m32ConnectDot{background:#38aee4;box-shadow:0 0 0 3px #123247}.m32ConnectForm{display:grid;grid-template-columns:1fr 110px;gap:8px}.m32ConnectInput{width:100%;background:#08131c;color:#fff;border:1px solid #304654;border-radius:12px;padding:12px 13px;font-size:14px}.m32ConnectBtn{border:1px solid #2d7ca2;background:linear-gradient(135deg,#135377,#1678a6);color:#f3fbff;border-radius:12px;font-weight:900;font-size:12px}.m32ConnectBtn.connected{border-color:#33805f;background:linear-gradient(135deg,#174d38,#1c704f)}.m32ConnectHint{font-size:10px;color:#8398a9;line-height:1.45}.realOnlyBadge{font-size:9px;border:1px solid #31536a;border-radius:99px;padding:4px 7px;color:#8fc9e7;background:#0d2230}
</style>
<script>
(function(){
window.__m32Connected=false;
function setM32UI(state,msg){const st=document.getElementById('m32ConnectState'),btn=document.getElementById('m32ConnectBtn');if(!st||!btn)return;st.classList.remove('connected','connecting');btn.classList.remove('connected');if(state==='connected'){st.classList.add('connected');st.innerHTML='<span class="m32ConnectDot"></span>CONNECTED';btn.classList.add('connected');btn.textContent='CONNECTED';window.__m32Connected=true}else if(state==='connecting'){st.classList.add('connecting');st.innerHTML='<span class="m32ConnectDot"></span>CONNECTING';btn.textContent='CONNECT...';window.__m32Connected=false}else{st.innerHTML='<span class="m32ConnectDot"></span>DISCONNECTED';btn.textContent='CONNECT';window.__m32Connected=false}const a=document.getElementById('proConnTitle'),b=document.getElementById('proConnSub');if(a)a.textContent=state==='connected'?'M32 CONNECTED':state==='connecting'?'CONNECTING TO M32':'M32 DISCONNECTED';if(b&&msg)b.textContent=msg}
window.connectM32=function(){const ipEl=document.getElementById('m32QuickIp');const ip=(ipEl?ipEl.value:'').trim();const port=parseInt(localStorage.port||'10023');if(!/^\d{1,3}(\.\d{1,3}){3}$/.test(ip)){try{toast('กรุณาใส่ IP ของ M32 ให้ถูกต้อง')}catch(e){}return}localStorage.ip=ip;localStorage.port=String(port);localStorage.target='real';try{target='real'}catch(e){}const a=document.getElementById('ip'),b=document.getElementById('port');if(a)a.value=ip;if(b)b.value=String(port);setM32UI('connecting','Checking '+ip+':'+port+' ...');try{WellNative.connectM32(ip,port)}catch(e){setM32UI('disconnected','Connection bridge unavailable')}};
window.onM32Connect=function(ok,msg){setM32UI(ok?'connected':'disconnected',ok?((localStorage.ip||'M32')+' • Ready'):(msg||'No response from M32'));try{toast(ok?'เชื่อมต่อ M32 สำเร็จ':'ไม่พบ M32 ตรวจสอบ Router / IP')}catch(e){}};
function install(){try{localStorage.target='real';target='real'}catch(e){}const t=document.getElementById('testlab');if(t)t.remove();const tt=document.querySelector('.tabs button[data-p="testlab"]');if(tt)tt.remove();const pt=document.getElementById('proTarget');if(pt&&pt.closest('.proCard'))pt.closest('.proCard').remove();const ts=document.getElementById('targetSel');if(ts&&ts.closest('.row'))ts.closest('.row').remove();const cst=document.querySelector('.csTest');if(cst&&cst.closest('.csCard'))cst.closest('.csCard').remove();document.querySelectorAll('button').forEach(b=>{const x=(b.textContent||'').trim().toUpperCase();if(x.includes('AUTO ANALYZE')||x.includes('TEST LAB'))b.remove()});const home=document.querySelector('#home .proHome');if(home&&!document.getElementById('m32ConnectPanel')){const p=document.createElement('div');p.id='m32ConnectPanel';p.className='m32ConnectPanel';p.innerHTML='<div class="m32ConnectHead"><div><div class="m32ConnectTitle">M32 CONNECTION <span class="realOnlyBadge">REAL MIXER</span></div><small>Same connection style as Well Auto EQ Pro</small></div><div id="m32ConnectState" class="m32ConnectState"><span class="m32ConnectDot"></span>DISCONNECTED</div></div><div class="m32ConnectForm"><input id="m32QuickIp" class="m32ConnectInput" inputmode="decimal" placeholder="M32 IP  •  192.168.1.100"><button id="m32ConnectBtn" class="m32ConnectBtn" onclick="connectM32()">CONNECT</button></div><div class="m32ConnectHint">M32R → LAN → Router • Phone/Tablet → Wi‑Fi Router เดียวกัน</div>';const st=home.querySelector('.proStatus');if(st)st.after(p);else home.prepend(p);document.getElementById('m32QuickIp').value=localStorage.ip||'192.168.1.100'}const settings=document.querySelector('#settings .panel');if(settings&&!document.getElementById('m32SettingsConnect')){const b=document.createElement('button');b.id='m32SettingsConnect';b.className='btn full';b.textContent='CONNECT TO M32';b.onclick=function(){const q=document.getElementById('m32QuickIp'),i=document.getElementById('ip');if(q&&i)q.value=i.value.trim();connectM32()};settings.appendChild(b)}try{setTarget=function(){localStorage.target='real';target='real'}}catch(e){}setM32UI('disconnected',localStorage.ip?('Saved IP '+localStorage.ip+' • Tap CONNECT'):'Enter M32 IP and tap CONNECT')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,80));else setTimeout(install,80);window.addEventListener('load',()=>setTimeout(install,350));
})();
</script>'''
    s=s.replace('</body>',addon+'</body>')
    s=s.replace('Professional Audio Assistant • Simulator + M32 Control','Professional Audio Assistant • M32R Control')
    HTML.write_text(s)

j=JAVA.read_text()
if 'connectM32(String ip, int port)' not in j:
    query='''    @JavascriptInterface public void query(String ip, int port, String address) {\n      send(ip, port, address, "none", "");\n    }\n'''
    repl='''    @JavascriptInterface public void connectM32(String ip, int port) {\n      io.execute(() -> {\n        DatagramSocket socket = null;\n        try {\n          InetAddress host = InetAddress.getByName(ip);\n          byte[] data = encodeOsc("/info", "none", "");\n          socket = new DatagramSocket();\n          socket.setSoTimeout(1600);\n          socket.send(new DatagramPacket(data, data.length, host, port));\n          byte[] buf = new byte[4096];\n          DatagramPacket reply = new DatagramPacket(buf, buf.length);\n          socket.receive(reply);\n          boolean ok = reply.getAddress().equals(host);\n          m32ConnectCallback(ok, ok ? "M32 replied from " + reply.getAddress().getHostAddress() : "Unexpected reply");\n        } catch (Exception e) {\n          m32ConnectCallback(false, safeMsg(e.getMessage()));\n        } finally {\n          if (socket != null) try { socket.close(); } catch (Exception ignored) {}\n        }\n      });\n    }\n\n    @JavascriptInterface public void query(String ip, int port, String address) {\n      send(ip, port, address, "none", "");\n    }\n'''
    if query not in j: raise SystemExit('query anchor not found')
    j=j.replace(query,repl,1)
    anchor='  public class NativeBridge {\n'
    helper='''  private void m32ConnectCallback(boolean ok, String message) {\n    String msg = safeMsg(message).replace("\\\\", "\\\\\\\\").replace("'", "\\\\'").replace("\\n", " ").replace("\\r", " ");\n    runOnUiThread(() -> webView.evaluateJavascript(\n        "window.onM32Connect&&window.onM32Connect(" + (ok ? "true" : "false") + ",'" + msg + "')", null\n    ));\n  }\n\n  public class NativeBridge {\n'''
    if anchor not in j: raise SystemExit('bridge anchor not found')
    j=j.replace(anchor,helper,1)
    JAVA.write_text(j)
